<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-10-04 05:17
=======
# Generated by Django 5.1.1 on 2024-10-03 21:07
>>>>>>> 6d935eaf2473f2ca095b21ac86f43d2ddbb1b9ab

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRADE',
            fields=[
                ('id_grade', models.IntegerField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=100)),
            ],
        ),
    ]
