# Generated by Django 5.1.1 on 2024-09-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='id_grade',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
