# Generated by Django 5.1.1 on 2024-09-29 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0002_alter_grade_id_grade'),
        ('instituto', '0001_initial'),
        ('user', '0005_remove_student_id_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_subsidy', models.BooleanField()),
                ('scholarship', models.BooleanField()),
                ('id_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.grade')),
                ('id_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.institutions')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
