# Generated by Django 5.1.1 on 2024-10-12 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0002_initial'),
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='psychologist_in_charge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pacient', to='psychologist.psychologist'),
        ),
    ]
