# Generated by Django 5.1.1 on 2024-10-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0001_initial'),
        ('psychologist', '0002_initial'),
        ('student', '0004_alter_student_id_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.institutions'),
        ),
        migrations.AlterField(
            model_name='student',
            name='psychologist_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacient', to='psychologist.psychologist'),
        ),
    ]
