# Generated by Django 5.1.1 on 2024-10-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('modification_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('response_date', models.DateField(auto_now_add=True)),
                ('like_count', models.IntegerField(default=0)),
            ],
        ),
    ]
