# Generated by Django 5.1.1 on 2024-10-04 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postresponse',
            name='USERS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_as_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postresponse',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_as_id_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postresponse',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='post.post'),
        ),
    ]
