# Generated by Django 5.1.1 on 2024-09-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='id_rol',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
