# Generated by Django 5.1.1 on 2024-09-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id_user', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=75)),
                ('usert_birth_date', models.DateField()),
                ('user_first_name', models.CharField(max_length=75)),
                ('user_last_name', models.CharField(max_length=75)),
                ('user_email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_phone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
