# Generated by Django 5.1.1 on 2024-09-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='lol',
            field=models.CharField(default='default_value', max_length=19),
            preserve_default=False,
        ),
    ]
