# Generated by Django 5.1.1 on 2024-09-25 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_users_lol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='lol',
        ),
    ]
