# Generated by Django 5.1.1 on 2024-09-25 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRADE',
            fields=[
                ('id_grade', models.AutoField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='INSTITUTIONS',
            fields=[
                ('id_institution', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=150)),
                ('public_institution', models.BooleanField()),
                ('institution_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ROL',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('dni_number', models.CharField(max_length=9, unique=True)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=75)),
                ('usert_birth_date', models.DateField()),
                ('user_first_name', models.CharField(max_length=75)),
                ('user_last_name', models.CharField(max_length=75)),
                ('user_email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_phone_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goberment_subsidy', models.BooleanField()),
                ('scholarship', models.BooleanField()),
                ('id_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.grade')),
                ('id_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.institutions')),
                ('rol_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.rol')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
        migrations.CreateModel(
            name='PSYCHOLOGIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.CharField(max_length=100)),
                ('aviability', models.BooleanField()),
                ('years_experience', models.IntegerField()),
                ('id_psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
