

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0002_alter_grade_id_grade'),
        ('rol', '0002_alter_rol_id_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='INSTITUTIONS',
            fields=[
                ('id_institution', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=150)),
                ('public_institution', models.BooleanField()),
                ('institution_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
                ('dni_number', models.CharField(max_length=9, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('crated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('birth_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.rol')),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gobernment_subsidy', models.BooleanField()),
                ('scholarship', models.BooleanField()),
                ('uuid', models.UUIDField(null=True, unique=True)),

                ('id_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.grade')),

                ('id_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='grade.grade')),


            ],
        ),
        migrations.CreateModel(
            name='PSYCHOLOGIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_code', models.CharField(max_length=100)),
                ('availability', models.BooleanField()),
                ('years_experience', models.IntegerField()),
                ('id_psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]

# Generated by Django 5.1.1 on 2024-10-01 10:05

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
                ('dni_number', models.CharField(max_length=9, unique=True)),
                ('sex', models.CharField(max_length=75)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('crated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('birth_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=8)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
