# Generated by Django 5.1.1 on 2024-09-27 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_alter_grade_id_grade'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='grade.grade'),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='paco', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GRADE',
        ),
    ]
