# Generated by Django 5.1.1 on 2024-09-29 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0001_initial'),
        ('user', '0002_rename_gobernment_subsidy_student_government_subsidy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.institutions'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='uuid',
        ),
        migrations.AddField(
            model_name='users',
            name='sex',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='INSTITUTIONS',
        ),
    ]
