# Generated by Django 5.1.1 on 2024-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_id_institution_remove_student_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(max_length=75),
        ),
    ]
