# Generated by Django 5.1.1 on 2024-09-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_institution',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_student',
        ),
        migrations.DeleteModel(
            name='PSYCHOLOGIST',
        ),
        migrations.DeleteModel(
            name='STUDENT',
        ),
    ]
