# Generated by Django 5.1.1 on 2024-10-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSYCHOLOGIST',
            fields=[
                ('id_psychologist', models.AutoField(primary_key=True, serialize=False)),
                ('license_code', models.CharField(max_length=100)),
                ('availability', models.BooleanField()),
                ('years_experience', models.IntegerField()),
            ],
        ),
    ]
