# Generated by Django 5.1.1 on 2024-10-02 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSYCHOLOGIST',
            fields=[
                ('id_psychologist', models.AutoField(primary_key=True, serialize=False)),
                ('license_code', models.CharField(max_length=100)),
                ('availability', models.BooleanField()),
                ('years_experience', models.IntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
