# Generated by Django 5.1.1 on 2024-10-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='pacient_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
