# Generated by Django 5.1.1 on 2024-10-14 21:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0004_psychologist_pacient_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EXPEDIENT',
            fields=[
                ('id_expedient', models.AutoField(primary_key=True, serialize=False)),
                ('observations', models.TextField(max_length=250)),
                ('crated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologist.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='PACIENTFILES',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('id_expedient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologist.expedient')),
            ],
        ),
    ]
