# Generated by Django 5.1.1 on 2024-10-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0005_expedient_pacientfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedient',
            name='observations',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
