# Generated by Django 5.1.1 on 2024-10-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0006_alter_expedient_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='pacient_count',
            field=models.IntegerField(default=0),
        ),
    ]
