# Generated by Django 5.1.1 on 2024-10-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0007_alter_psychologist_pacient_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedient',
            name='state',
            field=models.TextField(default='open', max_length=55),
        ),
    ]
