# Generated by Django 5.1.1 on 2024-10-25 21:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0008_expedient_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedient',
            name='observations',
        ),
        migrations.AddField(
            model_name='pacientfiles',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pacientfiles',
            name='file_name',
            field=models.CharField(default='archive', max_length=55),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OBSERVATIONS',
            fields=[
                ('id_observation', models.AutoField(primary_key=True, serialize=False)),
                ('observation_description', models.TextField(max_length=55)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_expedient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologist.expedient')),
            ],
        ),
    ]
