# Generated by Django 5.1.1 on 2024-10-27 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0009_remove_expedient_observations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='id_expedient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Observations', to='psychologist.expedient'),
        ),
        migrations.CreateModel(
            name='SESSIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_session', models.CharField(blank=True, max_length=100, null=True)),
                ('session_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_expedient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='psychologist.expedient')),
            ],
        ),
    ]
