# Generated by Django 5.1.1 on 2024-10-27 19:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0010_alter_observations_id_expedient_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observations',
            name='id_expedient',
        ),
        migrations.AlterField(
            model_name='observations',
            name='observation_description',
            field=models.TextField(max_length=255),
        ),
        migrations.CreateModel(
            name='SESSION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_session', models.CharField(blank=True, max_length=100, null=True)),
                ('session_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_expedient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologist.expedient')),
            ],
        ),
        migrations.AddField(
            model_name='observations',
            name='id_session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Sessions', to='psychologist.session'),
            preserve_default=False,
        ),
    ]
