# Generated by Django 5.1.1 on 2024-10-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0011_remove_observations_id_expedient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedient',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
