# Generated by Django 5.1.1 on 2024-10-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0012_rename_crated_at_expedient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='assigned_to_hotline',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
